// src/components/main/lanyard.tsx
"use client";

import { useLanyard } from "react-use-lanyard";
import { useEffect, useState } from "react";
import Link from "next/link";
import type { Activity } from "react-use-lanyard";

const statusMap = {
    online: "online",
    dnd: "on do not disturb",
    idle: "idle",
    offline: "offline",
};

const linkClassName =
    "text-foreground hover:text-muted transition-all duration-150 decoration-muted-foreground/30 hover:decoration-muted-foreground/50";

export function LanyardProfile() {
    const [mounted, setMounted] = useState(false);
    const { loading, status } = useLanyard({
        userId: "492731761680187403",
        socket: true,
    });

    const activities =
        status?.activities?.filter(
            (activity) => activity.type !== 4 && activity.type !== 2,
        ) || [];
    const hasSpotify = status?.listening_to_spotify;
    const hasActivities = activities.length > 0;

    useEffect(() => {
        setMounted(true);
    }, []);

    const getActivityText = (activity: Activity) => {
        if (activity.name === "Visual Studio Code") {
            const details = activity.details;
            if (details?.startsWith("In ")) {
                const projectMatch = details.match(/^In (.+?) -/);
                if (projectMatch) {
                    return `working on ${projectMatch[1]}`;
                }
            }
            return `working on ${activity.name}`;
        }
        return `playing ${activity.name}`;
    };

    const renderSpotifyContent = () => {
        if (!status?.spotify?.song || !status?.spotify?.artist) {
            return "listening to spotify";
        }

        return (
            <>
                listening to{" "}
                <Link
                    href={`https://open.spotify.com/track/${status.spotify.track_id}`}
                    target="_blank"
                    className={linkClassName}
                >
                    {status.spotify.song}
                </Link>{" "}
                by{" "}
                <Link
                    href={`https://open.spotify.com/search/${status.spotify.artist}`}
                    target="_blank"
                    className={linkClassName}
                >
                    {status.spotify.artist}
                </Link>{" "}
                on Spotify
            </>
        );
    };

    if (!mounted || loading || !status || !status.discord_user) {
        return (
            <span className="text-sm text-muted-foreground">
                Fetching Discord Presence...
            </span>
        );
    }

    return (
        <p className="text-sm text-muted-foreground">
            According to Discord, I am currently{" "}
            {statusMap[status.discord_status]}
            {hasActivities && hasSpotify && (
                <>
                    {" "}
                    {getActivityText(activities[0])} and{" "}
                    {renderSpotifyContent()}
                </>
            )}
            {hasActivities && !hasSpotify && (
                <> {getActivityText(activities[0])}</>
            )}
            {!hasActivities && hasSpotify && <> {renderSpotifyContent()}</>}.
        </p>
    );
}

// src/components/Lanyard.svelte
<script lang="ts">
import { onMount, onDestroy } from 'svelte'
import type { LanyardData } from '$lib/types/lanyard'

const statusDict: Record<string, string> = {
	online: 'Online',
	idle: 'Idle',
	dnd: 'Do Not Disturb',
	offline: 'Offline'
}

const statusColors: Record<string, string> = {
	online: 'text-green-200',
	idle: 'text-yellow-200',
	dnd: 'text-red-200',
	offline: 'text-gray-200'
}

let lanyard: LanyardData
let intervalId: number

async function updateLanyard() {
	const response = await fetch('https://api.lanyard.rest/v1/users/492731761680187403')
	lanyard = await response.json()
}

onMount(() => {
	updateLanyard()
	setInterval(() => {
		updateLanyard()
	}, 15000)
})

onDestroy(() => {
	clearInterval(intervalId)
})
</script>

<!-- TODO: RPC support? -->
<div class="text-sm">
	{#if lanyard}
		<div>
			<p>
				I'm currently
				<a
					class="link-underline font-semibold {statusColors[
						lanyard?.data.discord_status
					]}"
					href="https://discord.com/users/{lanyard?.data?.discord_user.id}"
					>{statusDict[lanyard?.data.discord_status]}</a>
				on Discord
				{#if lanyard?.data?.listening_to_spotify}
					- listening to
					<span class="inline-block">
						<a
							class="link-underline font-semibold text-white"
							href="https://open.spotify.com/track/{lanyard?.data?.spotify.track_id}"
							>{lanyard?.data?.spotify.song}</a>
						by
						<a
							class="link-underline font-semibold text-white"
							href="https://open.spotify.com/search/{lanyard?.data?.spotify.artist}"
							>{lanyard?.data?.spotify.artist}</a>
					</span>
				{/if}
			</p>
		</div>
	{:else}
		<div>
			<p class="animate-pulse">Loading Discord status...</p>
		</div>
	{/if}
</div>
